# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en

# Change to your timezone
timezone:

# jekyll-seo-tag settings
title: GitOps
tagline: "Networks, SDN, NFVi, OpenStack, K8s/OpenShift."

description: >-
  Networks, SDN, NFVi, OpenStack, K8s/OpenShift.

url: "https://josecastillolema.github.io"

github:
  username: josecastillolema

social:
  name: Jose Castillo Lema
  email: josecastillolema@gmail.com
  links:
    - https://github.com/josecastillolema
    - https://www.linkedin.com/in/jose-castillo-lema
    - https://stackoverflow.com/users/4288758/jos%c3%a9-castillo-lema
    - https://www.researchgate.net/profile/Jose_Castillo-Lema
    - https://scholar.google.com.br/citations?user=_xNpHiwAAAAJ
    - https://www.opennetworking.org/ambassadors/jose-castillo-lema/

# Site Verification Settings
webmaster_verifications:
  google: googled48a6d8a28aaa375

# Web Analytics Settings
analytics:
  google:
    id: "G-1EBHNQEGXG"

# Prefer color scheme setting.
theme_mode: # [light | dark]

# the avatar on sidebar
avatar: /assets/images/me.jpg

social_preview_image: /assets/images/favicon_io/android-chrome-512x512.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: disqus
  disqus:
    shortname: https-josecastillolema-github-io

pwa:
  enabled: false
  cache:
    enabled: false

paginate: 5

baseurl: ""

# Build output
destination: docs

# ------------ The following options are not recommended to be modified ------------------

markdown: kramdown

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Makefile
  - CLAUDE.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

jekyll-spaceship:
  processors:
    - mermaid-processor
    - emoji-processor
  mermaid-processor:
    syntax:
      code: 'mermaid'
